WATER_TEMP_SENSOR_PIN = 4
WATER_TEMP_SENSOR_TYPE = "DHT11"

# pumps
PUMP1_RELAY_PIN = 5
# PUMP2_RELAY_PIN = 18
# PUMP3_RELAY_PIN = 17

HEATER_RELAY_PIN = 2
BUBBLES_POTI_PIN = 34
COVER_BUTTON_PIN = 32

TARGET_TEMP = 35.0